#!/bin/sh
# File: get-files
case "${1}" in
   rpm)

### for rpm
find * -type d \
   \( \
      -regex 'usr\/share\/freefilesync.*' -o \
      -regex '.*icons.*' \
   \) \
   ! -regex '.*\/freefilesync\/FreeFileSync' \
   | sed -e 's/^/%dir \//;'
find * -mindepth 1 ! -name "${package}.spec.$$.swp" \
   \( \
      ! -type d -o \
      -regex '.*\/freefilesync\/FreeFileSync' \
   \) \
   ! -regex '.*?.swp' \
   ! -regex '.*?DEBIAN.*?' \
   | sed -e '
s/^/\//;
s/\(\(.*packaging\|.*README\)\.txt\)/%doc %attr(444, -, -) \1/;
s/\(.*CHANGELOG.*\)/%doc \1/;
s/\(.*\.ini\|.*xml\)/%config %attr(666, -, -) \1/;
s/\(.*\.desktop\)/%attr(666, -, -) \1/;
s/\(.*\/FreeFileSync$\)/%attr(777, -, -) \1/;
'

      ;;
   *)
      echo "FATAL ERROR: check ./pack or get-files. Please use [ rpm | deb ] option. Aborted." 1>&2
      exit 1
      ;;
esac
